<?php 
$price = $block->getPrice();
$installment = $block->getMaxMonthsPayin7Data();
?>

<?php if($price) { ?>
    <div class="payin7_category_list payin7_calculator categoryList" style="<?= $block->getStyle() ?>">
        <p>
            <img src="<?= $this->getViewFileUrl('Payin7_Mage2Payin7::images/logo_calculadora.png') ?>" alt=""/><br/>
            <span><?= __('DESDE') ?></span>
            <span class="payin7Price"><?= $price ?></span>
            <span><?= __('EN').' '.$installment['months'].' '.__('CUOTAS') ?></span>
            <span>(<?= __('%1 de gastos gestión incluidos en cada cuota',$block->formatPrice($installment['commission'])) ?>)<a href="#myModal"><sup>1</sup></a></span>
            <?php
            if($block->showTinTae()) {
            ?>
            <br/>(<?= __("TIN") ?> <?= $installment['tin'] ?>%, <?= __("TAE") ?> <?= $installment['tae'] ?>% )
            <br/><?= $block->getTextoImporteFinanciado().' '.$block->formatPrice($installment['months'] * $installment['amount']) ?>
            <?php
            }
            ?>
        </p>
    </div>
<?php } ?>